<?php
namespace Zhaiyujin\ScoutSearch\Facade;
use Illuminate\Support\Facades\Facade;
use Zhaiyujin\ScoutSearch\Search;
class Esearch extends Facade{

    public static function getFacadeAccessor()
    {
        // parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return Search::class;
    }


}
